tfrec_dir_train: /global/cscratch1/sd/xju/FourTop/WithPreselections/tfrec_btag/*.tfrec
tfrec_dir_val: /global/cscratch1/sd/xju/FourTop/WithPreselections/tfrec_btag_val/*.tfrec
output_dir:  /global/cscratch1/sd/xju/FourTop/WithPreselections/trained
prod_name: TESTSummary
model_name: GlobalClassifierNoEdgeInfo
loss_name: GlobalLoss
loss_args: 1, 1
parameters:
    batch_size: 1
    n_iters: 5
    learning_rate: 0.0001
    epochs: 2
    earlystop_metric: "auc_te" #auc_te, acc_te, pre_te, rec_te
    acceptable_failure: 5
    shuffle_buffer_size: 4
update_freq: 'batch' # how frequent the summary is written, 'batch', 'epoch', or 1000
do_profiling: true
profiling_batches: 10 # how many batches for profiling
