tfrec_dir_train: tfrec_train/*_*.tfrec
tfrec_dir_val: tfrec_val/*_*.tfrec
output_dir:  trained
prod_name: test3_reproduced_test1
model_name: DecaySimulator # don't change!
parameters:
    batch_size: 1
    learning_rate: 0.0001
    epochs: 100
    earlystop_metric: "auc_te" #auc_te, acc_te, pre_te, rec_te
    acceptable_failure: 5
