tfrec_dir_train: /global/cscratch1/sd/xju/WbosonTagger/tfrec_bigger/*_*.tfrec
tfrec_dir_val: /global/cscratch1/sd/xju/WbosonTagger/tfrec_val_bigger/*_*.tfrec
output_dir:  /global/cscratch1/sd/xju/WbosonTagger/trained
prod_name: noedge_fullevts_bigger
model_name: NodeEdgeClassifier
loss_name: NodeEdgeLoss, 2, 1, 2, 1
parameters:
    batch_size: 1
    n_iters: 5
    learning_rate: 0.0001
    epochs: 2
    earlystop_metric: "auc_te" #auc_te, acc_te, pre_te, rec_te
    acceptable_failure: 5
